/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NLW Connect
 * OpenAPI spec version: 0.1
 */
export type SubscribeToEventBody = {
  name: string
  email: string
  /** @nullable */
  referrer?: string | null
}

export type SubscribeToEvent201 = {
  subscriberId: string
}

/**
 * @nullable
 */
export type AccessInviteLink301 =
  | (typeof AccessInviteLink301)[keyof typeof AccessInviteLink301]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccessInviteLink301 = {
  null: 'null',
} as const

export type GetRanking200RankingItem = {
  id: string
  name: string
  score: number
}

export type GetRanking200 = {
  ranking: GetRanking200RankingItem[]
}

export type GetSubscriberInviteCount200 = {
  count: number
}

export type GetSubscriberInviteClicks200 = {
  count: number
}

export type GetSubscriberRankingPosition200 = {
  /** @nullable */
  position: number | null
}

/**
 * @summary Subscribe to event
 */
export const subscribeToEvent = () => {
  return { subscriberId: 'f4418d4a-76a9-4834-b6d9-20e4d41a5d54' }
}

/**
 * @summary Access invite link
 */
export const getAccessInviteLinkUrl = (subscriberId: string) => {
  return `http://localhost:3333/invites/${subscriberId}`
}

export const accessInviteLink = async (
  subscriberId: string,
  options?: RequestInit
): Promise<unknown> => {
  const res = await fetch(getAccessInviteLinkUrl(subscriberId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: unknown = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Get ranking
 */
export const getRanking = () => {
  return {
    ranking: [
      {
        id: '107680a9-9c68-436a-8d8f-0e0d68da92de',
        name: 'Rômulo B',
        score: 264,
      },
      {
        id: 'e6107e5b-45eb-4063-90f2-241538cd705c',
        name: 'Helly R.',
        score: 198,
      },
      {
        id: '1236f120-5a54-4df1-b596-079309be5b71',
        name: 'Mark S.',
        score: 143,
      },
    ],
  }
}

/**
 * @summary Get subscriber ranking invites count
 */
export const getSubscriberInviteCount = (subscriberId: string) => {
  return { count: '82' }
}

/**
 * @summary Get subscriber ranking invites clicks count
 */
export const getSubscriberInviteClicks = (subscriberId: string) => {
  return { count: '174' }
}

/**
 * @summary Get subscriber ranking position
 */
export const getSubscriberRankingPosition = (subscriberId: string) => {
  return { position: '14' }
}
